---
- name: Provision
  include: provision-{{ ansible_os_family }}.yml

- name: Time is in sync
  include: ntp-{{ ansible_os_family }}.yml

- name: Set SMTP server, hostname and timezone
  include: common-tasks.yml
