## REDHAT BLOCK

- name: NTP is installed
  yum:
    name: ntp
    state: present

- name: NTP servers configured
  blockinfile:
    dest: /etc/ntp.conf
    insertafter: '^# Please consider joining the pool \(http://www.pool.ntp.org/join.html\)\.$'
    block: |
      {{ ntp_servers }}
  notify: restart ntpd
  ignore_errors: "{{ ansible_check_mode }}"
  when: ntp_servers is defined

- name: NTP daemon is running
  service:
    name: ntpd
    state: started
    enabled: yes
