- name: NTP is installed
  zypper:
    name: ntp
    state: present

- name: NTP servers configured
  blockinfile:
    dest: /etc/ntp.conf
    insertafter: '^# server 127\.127\.8\.0 mode 5 prefer$'
    block: |
      {{ ntp_servers }}
  notify: restart ntpd
  ignore_errors: "{{ ansible_check_mode }}"
  when: ntp_servers is defined

- name: NTP daemon is running
  service:
    name: ntpd
    state: started
    enabled: yes
